#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=display_added action="sleep 2 && sketchybar --trigger space_change --trigger windows_on_spaces"
yabai -m signal --add event=display_removed action="sleep 1 && sketchybar --trigger space_change --trigger windows_on_spaces"

yabai -m config external_bar all:38:0

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus

yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_origin_display focused

yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow float

yabai -m config split_ratio 0.50
yabai -m config auto_balance off

yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config window_border_hidpi on
yabai -m config window_border_radius 11
yabai -m config window_border_blur off
yabai -m config active_window_border_color 0xfff2d5cf
yabai -m config normal_window_border_color 0xff51576d

yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config layout bsp
yabai -m config top_padding 4
yabai -m config bottom_padding 4
yabai -m config left_padding 4
yabai -m config right_padding 4
yabai -m config window_gap 6

yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^1Password for Safari$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Affinity Photo$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^AlDente$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Audio MIDI Setup$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" title="^(General|Accounts|Alerts|Advanced)$" manage=off
yabai -m rule --add app="^Clock$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Docker Desktop$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Finder$" title="^Finder Settings$" manage=off
yabai -m rule --add app="^Firefox$" title="^Library$" manage=off
yabai -m rule --add app="^NVIDIA GeForce NOW$" manage=off
yabai -m rule --add app="^Home$" manage=off
yabai -m rule --add app="^Mail$" title="^(General|Accounts|Junk Mail|Fonts & Colors|Viewing|Composing|Signatures|Rules|Extensions|Privacy)$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="^Nextcloud$" manage=off
yabai -m rule --add app="^Notes$" title="^Settings$" manage=off
yabai -m rule --add app="^Podcasts$" manage=off
yabai -m rule --add app="^Reminders$" manage=off
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advanced)$" manage=off
yabai -m rule --add app="^Screen Sharing$" manage=off
yabai -m rule --add app="^Slack$" manage=off
yabai -m rule --add app="^Sonos$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Things$" manage=off
yabai -m rule --add app="^Thunderbird$" title="Reminder" manage=off
yabai -m rule --add app="^Vimari$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off
yabai -m rule --add app="^Weather$" manage=off
yabai -m rule --add app="^WireGuard$" manage=off
yabai -m rule --add app="^zoom.us$" manage=off

echo "yabai configuration loaded.."
