#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=window_minimized action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

yabai -m config external_bar all:38:0

yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse autofocus

yabai -m config window_placement second_child
yabai -m config window_origin_display focused

yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.0
yabai -m config window_shadow float

yabai -m config split_ratio 0.50
yabai -m config auto_balance off

yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

yabai -m config layout bsp
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 10

yabai -m rule --add app="^1Password$" title="^Settings$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^AlDente$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Calendar$" title="^(General|Accounts|Alerts|Advanced)$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^Finder$" title="^Finder Settings$" manage=off
yabai -m rule --add app="^Infuse$" manage=off
yabai -m rule --add app="^Mail$" title="^(General|Accounts|Junk Mail|Fonts & Colors|Viewing|Composing|Signatures|Rules|Extensions|Privacy)$" manage=off
yabai -m rule --add app="^Minecraft Launcher$" manage=off
yabai -m rule --add app="^Nextcloud$" manage=off
yabai -m rule --add app="^Notes$" title="^Settings$" manage=off
yabai -m rule --add app="^Photo Booth$" manage=off
yabai -m rule --add app="^Safari$" title="^(General|(Tab|Password|Website|Profile|Extension|Feature Flag)s|AutoFill|Se(arch|curity)|Privacy|Advanced|Developer)$" manage=off
yabai -m rule --add app="^Screen Sharing$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^UTM$" manage=off
yabai -m rule --add app="^VLC$" manage=off

echo "yabai configuration loaded.."
